unique_ids:
  assets:
    standard-page.html: DE4B6PVYS4US524YABCVOIKZIZ2SD4ZS
    theme.css: XGOURA653T4RJAXSVF2GP53M5YZVBPWG
  forms:
    Form1: GRICT2OEZSXB2J6RIH74EUPBRJL63FQO
  modules: {}
  scripts: {}
  server_modules: {}
